# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-29 03:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='resort name')),
                ('location', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Resort_Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateField()),
                ('last_updated_time', models.CharField(max_length=50)),
                ('twelve_hour_snow', models.PositiveSmallIntegerField()),
                ('twenty4_hour_snow', models.PositiveSmallIntegerField()),
                ('base', models.PositiveSmallIntegerField()),
                ('total_snow', models.PositiveSmallIntegerField()),
                ('current_temp', models.SmallIntegerField()),
                ('current_weather', models.TextField()),
                ('forecast', models.TextField()),
                ('resort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resorts.Resort')),
            ],
        ),
        migrations.CreateModel(
            name='UAAC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.CharField(max_length=30)),
                ('area', models.CharField(max_length=30)),
                ('forcaster', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('advisory', models.TextField()),
                ('current_conditions', models.TextField()),
                ('weather', models.TextField()),
            ],
        ),
    ]
