# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-06 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resorts', '0003_auto_20180206_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resort_weather',
            name='last_updated_time',
            field=models.CharField(max_length=200),
        ),
    ]
