# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-06 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resorts', '0004_auto_20180206_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='UAAC_Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=30)),
                ('forcaster', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('advisory', models.TextField()),
                ('current_conditions', models.TextField()),
                ('weather', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='UAAC',
        ),
    ]
