# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-07 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resorts', '0006_auto_20180207_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uaac_report',
            name='area',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='uaac_report',
            name='forcaster',
            field=models.CharField(max_length=100),
        ),
    ]
