# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-09 00:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resorts', '0008_resort_weather_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resort_weather',
            name='date_time',
        ),
        migrations.AlterField(
            model_name='resort_weather',
            name='last_updated',
            field=models.DateTimeField(),
        ),
    ]
