# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-09 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resorts', '0009_auto_20180209_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uaac_report',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
