# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-14 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resorts', '0010_auto_20180209_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resort_weather',
            name='total_snow',
            field=models.CharField(max_length=50),
        ),
    ]
