# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-22 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resorts', '0011_auto_20180214_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resort_weather',
            name='base',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='resort_weather',
            name='current_temp',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='resort_weather',
            name='twelve_hour_snow',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='resort_weather',
            name='twenty4_hour_snow',
            field=models.CharField(max_length=50),
        ),
    ]
