# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-13 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resorts', '0012_auto_20180222_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='uaac_report',
            name='recent_activity',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
    ]
